spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_LOGINID}
            client-secret: ${SOCIAL_LOGINPASS}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

---

logging:
  level:
    org.springframework.security: DEBUG
  file:
    path: ./logs

---

kakao:
  map:
    host: https://dapi.kakao.com
    coord2address-uri: /v2/local/geo/coord2address.json
    rest-api-key: ${KAKAO_REST_API_KEY}

---

aws:
  s3:
    access:
      key: ${AWS_S3_ACCESS_KEY}
    secret:
      key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: buddyspace

---

app:
  default:
    profile-image: profile/default.png
    group-cover:
      online: group-cover/default_online.png
      offline: group-cover/default_offline.png
      hybrid: group-cover/default_hybrid.png
  invite:
    base:
      url: http://localhost:8080/test/group/invite?code=
  oauth2:
    redirect-uri: http://localhost:3000/auth/callback

---

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

---

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api-ui
    url: /api-docs
    disable-swagger-default-url: true
    doc-expansion: list
  paths-to-match:
    - /api/**

---