spring:
  profiles:
    group:
      local: "local"
      deploy: "deploy"
  jackson:
    time-zone: Asia/Seoul

kakao:
  map:
    host: https://dapi.kakao.com
    coord2address-uri: /v2/local/geo/coord2address.json
    rest-api-key: ${KAKAO_REST_API_KEY}

aws:
  s3:
    access:
      key: ${AWS_S3_ACCESS_KEY}
    secret:
      key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: buddyspace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_LOGINID}
            client-secret: ${SOCIAL_LOGINPASS}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    org.springframework.security: DEBUG


#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/mydatabase

---

spring:
  config:
    activate:
      on-profile: "deploy"
  datasource:
    url: jdbc:postgresql://postgres:5432/${DEPLOY_DB_NAME}
    username: ${DEPLOY_DB_USERNAME}
    password: ${DEPLOY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://mongodb:27017/${DEPLOY_MONGO_DB_NAME}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_LOGINID}
            client-secret: ${SOCIAL_LOGINPASS}
            scope:
              - email
              - profile
            redirect-uri: https://api.budderz.co.kr/login/oauth2/code/google
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
