spring:
  config:
    activate:
      on-profile: "deploy"
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:postgresql://postgres:5432/${DEPLOY_DB_NAME}
    username: ${DEPLOY_DB_USERNAME}
    password: ${DEPLOY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://mongodb:27017/${DEPLOY_MONGO_DB_NAME}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SOCIAL_LOGINID}
            client-secret: ${SOCIAL_LOGINPASS}
            scope:
              - email
              - profile
            redirect-uri: ${SOCIAL_LOGIN_REDIRECT_URI}
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

logging:
  level:
    root: INFO
    team.budderz.buddyspace: DEBUG
    org.springframework: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: /var/log/app
    name: spring-app.log

kakao:
  map:
    host: https://dapi.kakao.com
    coord2address-uri: /v2/local/geo/coord2address.json
    rest-api-key: ${KAKAO_REST_API_KEY}

aws:
  s3:
    access:
      key: ${AWS_S3_ACCESS_KEY}
    secret:
      key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: buddyspace

app:
  default:
    profile-image: profile/default.png
    group-cover:
      online: group-cover/default_online.png
      offline: group-cover/default_offline.png
      hybrid: group-cover/default_hybrid.png
  invite:
    base:
      url: https://budderz.co.kr/invite?code=

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

---

spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB

---

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api-ui
    url: /api-docs
    disable-swagger-default-url: true
    doc-expansion: list
  paths-to-match:
    - /api/**

---

